### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by lobbyit80** [EtheaDev/DelphiShellControlsPackages#1]
I followed the installation instructions, but it always gives the following error message on community edition version 11:

Registration procedure, Shellreg.Register in package C:\Users\Public\Documents\Emabercadero\Studio\22.0\Bpl\dclshlctrls280.bpl raised exception class EAccessViolation: Access violation ad address 6CDC8333 in module 'rtl280.bpl'. Read of address 00010109

**Comment by carloBarazzetta** [comment]
I have no problem with Delphi 11 Community Edition...
![image](https://github.com/EtheaDev/DelphiShellControlsPackages/assets/7803548/8a4c2591-0921-42ef-b28a-3492b63e6f97)
Try to uninstall package, rebuild and reinstall...

**Comment by carloBarazzetta** [comment]
Any feedback?
